### ISSUE TITLE
     myIsolates .(2 ) FUTURE ERROR: 86: COMMUNICATIONS FAILURE 1119  ERR_CLOSED : Socket Closed while receiving

### ISSUE THREAD

**Issue by norberturkiewicz** [Dyalog/isolate#1]
Any idea what might be causing this?

**FUTURE ERROR: 86: COMMUNICATIONS FAILURE 1119  ERR_CLOSED : Socket Closed while receiving: iEvaluate[13] (,⍕(⍕rc),': ',(0⊃res),{(⍵∨.≠' ')/': ',⍵}1⊃res,'' '')iSpace.qsignal rc**

 runTests←{
     ⍺←0
     ⎕THIS.myIsolates←⍺{
         ~⍺:0
         ok←⎕CY'isolate'
         {isolate.New''}¨⍳4
     }''

}

     myIsolates .(2 )
FUTURE ERROR: 86: COMMUNICATIONS FAILURE 1119  ERR_CLOSED : Socket Closed while receiving: iEvaluate[13] (,⍕(⍕rc),': ',(0⊃res),{(⍵∨.≠' ')/': ',⍵}1⊃res,'' '')iSpace.qsignal rc
      myIsolates.(2)

**Comment by mkromberg** [comment]
I think this is #31, which is fixed in v19.0 and will be patched in older versions.
